parameters:
#    ndj_user.example.class: ndj\UserBundle\Example

services:
#    ndj_user.example:
#        class: %ndj_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
