<?php

namespace ndj\DGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AventurierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AventurierRepository extends EntityRepository
{
	public function findInDonjon($iddonjon)
	{		
		return $this->_em
			->createQuery('SELECT a FROM ndjDGameBundle:Aventurier a, ndjDGameBundle:Etage e, ndjDGameBundle:Piece p   
					WHERE
							a.idpiece = p.id 
					AND 	p.idetage = e.id
					AND		e.iddonjon = :iddonjon ')
			->setParameter('iddonjon', $iddonjon)
			->getResult();
	}
}
