<?php

namespace ndj\DGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnecteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnecteRepository extends EntityRepository
{
}
