<?php

namespace ndj\DGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DonjonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonjonRepository extends EntityRepository
{
	//public function findBy($criteria,$orderBy=null,$limit,$offset)
	public function findByStats($key, $limit=3)
	{
		/*
		 SELECT D.* FROM DONJON D, STATS S WHERE D.ETAT=2 AND S.CLE="'.$mode.'" AND CONCAT(D.idDONJON,":d")=S.USR ORDER BY S.VAL DESC LIMIT '.$limit
		 */
		$query = $this->getEntityManager()
			->createQuery("SELECT d FROM ndjDGameBundle:Donjon d, ndjDGameBundle:Stats s
					WHERE d.etat=2
					AND s.cle = :cle
					AND CONCAT(d.id,':d')=s.usr
					ORDER BY s.val DESC")
			->setParameter('cle', $key)
			->setMaxResults($limit);
		
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
