<?php

namespace ndj\DGameBundle\Repository;

use ndj\DGameBundle\Entity\Donjon;

use Doctrine\ORM\EntityRepository;

/**
 * EtageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtageRepository extends EntityRepository
{
	public function getNextNiveau(Donjon $donjon, $o)
	{
	/*
			if ($o == 'p')
			{
				$sql = 'SELECT MAX(Niveau)+1 FROM ETAGE';
			}
			else //if ($_GET['o'] == 'm')
			{
				$sql = 'SELECT MIN(Niveau)-1 FROM ETAGE';
			}
	*/
		return $this->_em
			->createQuery('SELECT '
					.(($o=='p')? ' MAX(e.niveau)+1 ': ' MIN(e.niveau)-1 ')
					.' AS n FROM ndjDGameBundle:Etage e WHERE e.iddonjon=:iddonjon')
					
			->setParameter('iddonjon', $donjon->getId())
			->getSingleResult();
	}
}
