<?php

namespace ndj\DGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
	public function findListByPlayer($key, $offset=0, $size=20)
	{
		
		$query = $this->getEntityManager()
		->createQuery("
				SELECT e FROM ndjDGameBundle:Evenement e
				WHERE 	e.content != ''
					AND	e.cat IN (0,1,2)
					AND	e.dest = :usr
				ORDER BY e.dt DESC ")
		->setParameter('usr', $key)
		->setMaxResults($size)
		->setFirstResult($offset);
		
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			echo $e;
			return null;
		}
	}
}
