<?php

namespace ndj\DGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InventaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireRepository extends EntityRepository
{
	public function findByIdDonjon($iddonjon)
	{
		$query = $this->getEntityManager()
			->createQuery('
				SELECT i FROM ndjDGameBundle:Inventaire i 
				WHERE i.iddonjon = :id'
			)->setParameter('id', $iddonjon);
		
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
	
	public function findCommerceBoutique($categories)
	{
		$query = $this->getEntityManager()
		->createQuery("
				SELECT i FROM ndjDGameBundle:Inventaire i, ndjDGameBundle:Objets o
				WHERE i.iddonjon IS NULL
				AND	i.idaventurier IS NULL
				AND	i.idcompte IS NULL
				AND	i.idbestiaire IS NULL
				AND i.idobjets=o.id
				AND o.cat IN ( :cat )"
		)->setParameter('cat', $categories);
	
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			echo $e;
			return null;
		}
	}
	
	public function findCommerceOccasion()
	{
		$query = $this->getEntityManager()
		->createQuery(" SELECT i FROM ndjDGameBundle:Inventaire i WHERE (
	i.iddonjon IS NOT NULL
	OR 	i.idaventurier IS NOT NULL
	OR 	i.idbestiaire IS NOT NULL
	OR 	i.idcompte IS NOT NULL )
	AND i.position='{V}' ");
	
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			echo $e;
			return null;
		}
	}
}
