<?php

namespace ndj\DGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends EntityRepository
{
	public function findByIdDonjon($iddonjon)
	{
		return $this->_em
			->createQuery('SELECT p FROM ndjDGameBundle:Piece p, ndjDGameBundle:Etage e WHERE p.idetage=e.id AND e.iddonjon=:iddonjon ORDER BY p.idetage')
			->setParameter('iddonjon', $iddonjon)
			->getResult();
	}
}
